### PR TITLE
Quick fixup to make the module useful again.

### LINKED ISSUE #3: got error while installation
**Describe the bug**
# npm resolution error report

```
2023-09-05T06:34:09.724Z

While resolving: undefined@undefined
Found: react@16.14.0
node_modules/react
  peer react@"16.x" from react-native-webrtc-web-shim@1.0.3
  node_modules/react-native-webrtc-web-shim
    react-native-webrtc-web-shim@"*" from the root project

Could not resolve dependency:
peer react@"18.2.0" from react-native@0.72.4
node_modules/react-native
  peer react-native@"0.x" from react-native-webrtc-web-shim@1.0.3
  node_modules/react-native-webrtc-web-shim
    react-native-webrtc-web-shim@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "react",
    "version": "16.14.0",
    "whileInstalling": {
      "path": "C:\\Users\\Jigar\\Desktop\\College Project"
    },
    "location": "node_modules/react",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "peer",
        "name": "react",
        "spec": "16.x",
        "from": {
          "name": "react-native-webrtc-web-shim",
          "version": "1.0.3",
          "whileInstalling": {
            "path": "C:\\Users\\Jigar\\Desktop\\College Project"
          },
          "location": "node_modules/react-native-webrtc-web-shim",
          "isWorkspace": false,
          "dependents": [
            {
              "type": "prod",
              "name": "react-native-webrtc-web-shim",
              "spec": "*",
              "from": {
                "location": "C:\\Users\\Jigar\\Desktop\\College Project"
              }
            }
          ]
        }
      }
    ]
  },
  "currentEdge": null,
  "edge": {
    "type": "peer",
    "name": "react",
    "spec": "18.2.0",
    "error": "INVALID",
    "from": {
      "name": "react-native",
      "version": "0.72.4",
      "whileInstalling": {
        "path": "C:\\Users\\Jigar\\Desktop\\College Project"
      },
      "location": "node_modules/react-native",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "peer",
          "name": "react-native",
          "spec": "0.x",
          "from": {
            "name": "react-native-webrtc-web-shim",
            "version": "1.0.3",
            "whileInstalling": {
              "path": "C:\\Users\\Jigar\\Desktop\\College Project"
            },
            "location": "node_modules/react-native-webrtc-web-shim",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "prod",
                "name": "react-native-webrtc-web-shim",
                "spec": "*",
                "from": {
                  "location": "C:\\Users\\Jigar\\Desktop\\College Project"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false
}
```

**Instructions To reproduce**

This Issue with `react@18.2.0`

**Versions (please complete the following information):**

- React Native Version:0.72.4
- React Native Web Version:~0.19.6
- React Native WebRTC Version:^111.0.3

### PR DESCRIPTION
**Pull request by 8BallBomBom**
I feel that we actually need a TypeScript remake and a proper cleanup.
But this should do for now 👍🏻 

Fixes #3.

### CODE REVIEW

**Comment by saghul** [comment]
Feel free to land it when the CI is happy :-)

**Comment by 8BallBomBom** [comment]
Ahahahaha that is a good one 🤔 will investigate.
But will also need permissions nudging up 😅

**Comment by saghul** [comment]
Fixed the permissions :-)

**Comment by 8BallBomBom** [comment]
Thanks as always, will see what i can do 👍🏻

**Comment by OlliePugh** [comment]
I can't see the CI for this, but is there any idea of when this will get merged? 🙏

**Comment by 8BallBomBom** [comment]
Technically it could be merged now, just the CI being a bit funky.
But there is another issue that i'm trying to resolve relating to releasing the update on the registry.

**Comment by OlliePugh** [comment]
Ahh okay, where is the CI? I can't see github actions running on this PR? 🤔

**Comment by 8BallBomBom** [comment]
Pretty much binned them until i was sure of things actually working but they will run again soon.
Chances are the browser tests might be thrown out and replaced with nothing or an updated alternative.

**Comment by 8BallBomBom** [comment]
Going to push this up, do a release and fix the GH Actions at a later time.
Only real issue though is getting the package updated and released properly on the main NPM Registry.

**Pull request merged**
